# Generated by Django 5.2.6 on 2025-09-24 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('narration', models.TextField(blank=True)),
                ('udf_values', models.JSONField(blank=True, default=dict)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher_system.journaltype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher_system.organization')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('narration', models.TextField(blank=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('udf_values', models.JSONField(blank=True, default=dict)),
                ('line_number', models.IntegerField(default=1)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='voucher_system.journal')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherModeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('layout_style', models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('detailed', 'Detailed')], default='standard', max_length=20)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('default_narration_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher_system.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='voucher_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher_system.vouchermodeconfig'),
        ),
        migrations.CreateModel(
            name='VoucherModeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('narration', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('voucher_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='voucher_system.vouchermodeconfig')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherUDFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date Time'), ('select', 'Select'), ('multiselect', 'Multi Select'), ('checkbox', 'Checkbox'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], max_length=20)),
                ('scope', models.CharField(choices=[('header', 'Header'), ('line', 'Line')], max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True)),
                ('help_text', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=500)),
                ('choices_config', models.JSONField(blank=True, default=dict)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher_system.organization')),
                ('voucher_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udf_configs', to='voucher_system.vouchermodeconfig')),
            ],
            options={
                'unique_together': {('voucher_config', 'field_name', 'scope')},
            },
        ),
    ]
